RELATIONSHIP_NAMES = {
    'en': [
        'Identity', 'Duality', 'Activation', 'Mirror', 'Benefactor', 'Supervisee',
        'Business', 'Mediator', 'Quasi-identity', 'Extinguishment', 'Conflict',
        'Beneficiary', 'Supervisor', 'Kindred', 'Semi-duality', 'Activation'
    ],
    'es': [
        'Identidad', 'Dualidad', 'Activación', 'Espejo', 'Benefactor', 'Supervisado',
        'Negocios', 'Mediador', 'Casi-identidad', 'Extinguimiento', 'Conflicto',
        'Beneficiario', 'Supervisor', 'Afinidad', 'Semi-dualidad', 'Activación'
    ],
    'uk': [
        'Тотожність', 'Дуальність', 'Активація', 'Дзеркало', 'Благодійник', 'Супервізор',
        'Бізнес', 'Медіатор', 'Квазі-тотожність', 'Загасання', 'Конфлікт',
        'Бенефіціар', 'Супервізований', 'Родич', 'Півдуальність', 'Активація'
    ]
}

RELATIONSHIP_DESCRIPTIONS = {
    'en': [
        'These partners are very similar in their abilities and the way they look at the world as many of the same traits are shared. This relationship is the easiest to form and will succeed when there is a need to transfer accumulated knowledge and experience back and forth. Both will have complete understanding but due to similarities will be largely unable to help the other with identical problems.',
        'Interaction is generally rewarding and satisfying for both, providing each other with inspiration and support. This is often considered the most beneficial relation as all interactions are complementary, providing an “other half” effect.',
        'Partners raise the overall energy level, serve to mobilize one another. However, these partners tend to overactivate each other over time and can do with breaks in order to cool down.',
        'Partners will feel as though they are looking in the mirror, seeing a reflection of their motives; will have similar actions and motivations, and can reach mutual understanding quite easily. However, levels of energy and discipline will be reversed, resulting in different lifestyles. They are likely to have slightly different takes on the same issue and may mutually correct each other. While mostly affable, sometimes, this can result in minor clashes.',
        'Both partners greatly admire each other. However, there is an asymmetry: the benefactor is able to help the beneficiary but not the other way around. As a result, these relations are often temporary, with a sense of unfairness being felt over time by the benefactor and a sense of uselessness being felt by the beneficiary.',
        'This is an asymmetric relationship, in which one partner is constantly seen as lacking in some required area by the other. As a result, the supervisee feels somewhat wary or careful about their words and actions around the supervisor, feeling that they could be corrected in an area they feel insecure about.',
        'Both partners understand each other very well and are usually happy to interact. But, in general, this is a pair of people with very different goals.',
        'These relationships are usually pleasant, but only for mutual leisure time. It is difficult to accomplish something serious together because their individual goals continually undo each other.',
        'These are relationships built on mutual respect. Each partner sees qualities in the other that are desired. But they must maintain some psychological distance, because one-on-one, they can start to annoy one another. Although having very similar energy levels and lifestyles, they have very different abilities and life values, leading to misunderstanding.',
        'These partners have many common interests, but are often confused by each other`s seemingly counter-intuitive insights. Their thinking styles are very different despite being good at similar things. Each may often feel that they other is deliberately trying to undermine or extinguish their approach, but this is not intentionally the case.',
        'Partners` interests are aligned, but at a closer distance misunderstandings arise. Collaborative work with ample room to move, regarding process and approach, is necessary for success in this pair. Working in close contact will lead to confusion due to the very different values and attitudes these partners have. They will not take each other`s advice as they each perceive themselves as doing the same as the other, only better.',
        'Misunderstandings arise very easily in this type of relationship. The two partners are exact opposites in abilities, temperament and life values, resulting in there being very little in common. Despite being initially attracted to each other due to them providing in certain amounts what the other partner needs in their life, they soon realise that the value dissonance makes relations mutually painful, with each putting pressure upon the other`s points of insecurity rather than protecting and helping those points.',
        'Both partners greatly admire each other. However, there is an asymmetry: the benefactor is able to help the beneficiary but not the other way around. As a result, these relations are often temporary, with a sense of unfairness being felt over time by the benefactor and a sense of uselessness being felt by the beneficiary. ',
        'This is an asymmetric relationship, in which one partner is constantly seen as lacking in some required area by the other. As a result, the supervisee feels somewhat wary or careful about their words and actions around the supervisor, feeling that they could be corrected in an area they feel insecure about.',
        'Partners like to discuss similar topics and often have many common interests. But when they come to practical implementation of their mutual goals and projects, each finds that the other acts in contrary ways.',
        'Relationships of semi-duality can become very close for moderate periods of time. Often these relations lead to friendship and fruitful cooperation at work. But very close relationships can lead to disappointments.'
    ],
    'es': [
        'Estos socios son muy similares en sus habilidades y en la forma en que ven el mundo, ya que comparten muchos de los mismos rasgos. Esta relación es la más fácil de formar y tendrá éxito cuando haya una necesidad de transferir conocimientos y experiencia acumulados de ida y vuelta. Ambos tendrán una comprensión completa, pero debido a las similitudes, no podrán ayudar al otro con problemas idénticos.',
        'La interacción es generalmente gratificante y satisfactoria para ambos, brindándose inspiración y apoyo mutuo. Esta es a menudo considerada la relación más beneficiosa, ya que todas las interacciones son complementarias, proporcionando un efecto de "media naranja".',
        'Los socios aumentan el nivel de energía general, sirven para movilizarse mutuamente. Sin embargo, estos socios tienden a sobreactivarse con el tiempo y pueden hacerlo con descansos para enfriarse.',
        'Los socios sentirán que se están mirando en el espejo, viendo un reflejo de sus motivos; tendrán acciones y motivaciones similares, y pueden llegar a un entendimiento mutuo con bastante facilidad. Sin embargo, los niveles de energía y disciplina se invertirán, lo que resultará en diferentes estilos de vida. Es probable que tengan opiniones ligeramente diferentes sobre el mismo tema y pueden corregirse mutuamente. Si bien es principalmente afable, a veces esto puede resultar en pequeños choques.',
        'Ambos socios se admiran mucho. Sin embargo, hay una asimetría: el benefactor puede ayudar al beneficiario pero no al revés. Como resultado, estas relaciones suelen ser temporales, con una sensación de injusticia que se siente con el tiempo por el benefactor y una sensación de inutilidad que se siente por el beneficiario.',
        'Esta es una relación asimétrica, en la que un socio es constantemente visto como carente en algún área requerida por el otro. Como resultado, el supervisado se siente algo cauteloso o cuidadoso con sus palabras y acciones en torno al supervisor, sintiendo que podrían corregirlo en un área en la que se siente inseguro.',
        'Ambos socios se entienden muy bien y generalmente están felices de interactuar. Pero, en general, este es un par de personas con objetivos muy diferentes.',
        'Estas relaciones suelen ser agradables, pero solo para el tiempo libre mutuo. Es difícil lograr algo serio juntos porque sus objetivos individuales se deshacen continuamente entre sí.',
        'Estas son relaciones construidas sobre el respeto mutuo. Cada socio ve cualidades en el otro que son deseadas. Pero deben mantener cierta distancia psicológica, porque uno a uno, pueden comenzar a molestarse mutuamente. Aunque tienen niveles de energía y estilos de vida muy similares, tienen habilidades y valores de vida muy diferentes, lo que lleva a malentendidos.',
        'Estos socios tienen muchos intereses comunes, pero a menudo se confunden por las ideas aparentemente contra intuitivas del otro. Sus estilos de pensamiento son muy diferentes a pesar de ser buenos en cosas similares. Cada uno puede sentir a menudo que el otro está tratando deliberadamente de socavar o extinguir su enfoque, pero este no es el caso intencionalmente.',
        'Los intereses de los socios están alineados, pero a una distancia más cercana surgen malentendidos. El trabajo colaborativo con mucho espacio para moverse, en cuanto a proceso y enfoque, es necesario para el éxito en este par. Trabajar en contacto cercano provocará confusión debido a los valores y actitudes muy diferentes que tienen estos socios. No tomarán los consejos del otro ya que cada uno se percibe a sí mismo como haciendo lo mismo que el otro, solo que mejor.',
        'Los malentendidos surgen muy fácilmente en este tipo de relación. Los dos socios son opuestos exactos en habilidades, temperamento y valores de vida, lo que resulta en que tengan muy poco en común. A pesar de ser atraídos inicialmente el uno al otro debido a que proporcionan en cierta medida lo que el otro socio necesita en su vida, pronto se dan cuenta de que la disonancia de valores hace que las relaciones sean mutuamente dolorosas, ya que cada uno ejerce presión sobre los puntos de inseguridad del otro en lugar de proteger y ayudar a esos puntos.',
        'Ambos socios se admiran mucho. Sin embargo, hay una asimetría: el benefactor puede ayudar al beneficiario pero no al revés. Como resultado, estas relaciones suelen ser temporales, con una sensación de injusticia que se siente con el tiempo por el benefactor y una sensación de inutilidad que se siente por el beneficiario.',
        'Esta es una relación asimétrica, en la que un socio es constantemente visto como carente en algún área requerida por el otro. Como resultado, el supervisado se siente algo cauteloso o cuidadoso con sus palabras y acciones en torno al supervisor, sintiendo que podrían corregirlo en un área en la que se siente inseguro.',
        'A los socios les gusta discutir temas similares y a menudo tienen muchos intereses comunes. Pero cuando llegan a la implementación práctica de sus objetivos y proyectos mutuos, cada uno descubre que el otro actúa de manera contraria.',
        'Las relaciones de semi-dualidad pueden volverse muy cercanas durante períodos moderados de tiempo. A menudo estas relaciones llevan a la amistad y una cooperación fructífera en el trabajo. Pero las relaciones muy cercanas pueden llevar a decepciones.',
    ],
    'uk': [
        'Ці партнери дуже схожі за своїми здібностями та способом бачення світу, оскільки вони діляться багатьма спільними рисами. Ця взаємодія найлегше формується та буде успішною, коли є потреба передавати накопичені знання та досвід туди й сюди. Обидва будуть міцно розуміти один одного, але через подібність не зможуть допомогти один одному з ідентичними проблемами.',
        'Взаємодія зазвичай є насолодою та задоволенням для обох сторін, надаючи один одному натхнення та підтримку. Це часто вважається найбільш корисним відношенням, оскільки всі взаємодії є доповнюючими, створюючи ефект "іншої половинки".',
        'Партнери підвищують загальний рівень енергії, служать для мобілізації один одного. Проте з часом ці партнери мають тенденцію перенапружувати один одного, і їм потрібні перерви, щоб охолодитися.',
        'Партнери будуть відчувати, що дивляться в дзеркало, бачачи відбиток своїх мотивів; вони матимуть схожі дії та мотивації і зможуть досить легко досягти взаєморозуміння. Однак рівні енергії та дисципліни будуть перевернуті, що призведе до різних стилів життя. Ймовірно, вони матимуть трохи різний підхід до тієї ж проблеми й можуть коригувати один одного. Хоча в основному це може призводити до незначних зіткнень.',
        'Обидва партнери дуже захоплюються один одним. Проте є асиметрія: благодійник може допомогти бенефіціару, але не навпаки. У результаті такі відносини часто є тимчасовими, і з часом благодійник відчуває негоду за недопомогу, а бенефіціар відчуває непотрібність.',
        'Це асиметричні відносини, в яких одного партнера постійно вважають недостатнім у деякій області іншим. В результаті супервізор відчуває деяку обережність або старанність у висловлюваннях і діях навколо супервізора, відчуваючи, що його можуть виправити в області, де він відчуває себе незахищеним.',
        'Обидва партнери дуже добре розуміють один одного та зазвичай задовольняються взаємодією. Але загалом це пара людей з дуже різними цілями.',
        'Ці відносини зазвичай приємні, але тільки для взаємного дозвілля. Важко досягти чогось серйозного разом, оскільки їхні індивідуальні цілі постійно скасовують одна одну.',
        'Ці відносини побудовані на взаємному повазі. Кожен партнер бачить в іншому бажані якості. Але вони повинні підтримувати певну психологічну відстань, оскільки один на одного вони можуть почати дратуватися. Хоча вони мають дуже схожі рівні енергії та стилі життя, вони мають дуже різні здібності та життєві цінності, що призводить до непорозумінь.',
        'Ці партнери мають багато спільних інтересів, але часто збентежені видимо суперечними ідеями один одного. Їх стилі мислення дуже різні, незважаючи на те, що вони добрі в схожих речах. Кожен з них часто може відчувати, що інший намагається свідомо підірвати або приглушити його підхід, але це не влаштовується навмисно.',
        'Інтереси партнерів узгоджені, але на ближчій відстані виникають непорозуміння. Спільна робота з великим простором для дій, щодо процесу та підходу, необхідна для успіху цієї пари. Робота в тісному контакті призведе до збентеження через дуже різні цінності та відношення цих партнерів. Вони не приймуть поради один одного, оскільки кожен сприймає себе таким, що робить те ж саме, що інший, тільки краще.',
        'Непорозуміння дуже легко виникають у цьому типі відносин. Обидва партнери є точними протилежностями за здібностями, темпераментом та цінностями життя, що призводить до того, що між ними мало спільного. Незважаючи на те, що на початку вони притягуються один до одного через те, що надають один одному певну кількість того, що потрібно іншому партнерові в їхньому житті, вони вже скоро розуміють, що розбіжність цінностей робить взаємини болючими, оскільки кожен ставить тиск на точки незахищеності іншого замість їх захисту та допомоги.',
        'Обидва партнери дуже захоплюються один одним. Проте є асиметрія: благодійник може допомогти бенефіціару, але не навпаки. У результаті такі відносини часто є тимчасовими, і з часом благодійник відчуває негоду за недопомогу, а бенефіціар відчуває непотрібність.',
        'Це асиметричні відносини, в яких одного партнера постійно вважають недостатнім у деякій області іншим. В результаті супервізор відчуває деяку обережність або старанність у висловлюваннях і діях навколо супервізора, відчуваючи, що його можуть виправити в області, де він відчуває себе незахищеним.',
        'Партнерам подобається обговорювати схожі теми і часто мають багато спільних інтересів. Але коли приходить до практичної реалізації їхніх спільних цілей та проектів, кожен з них виявляє, що інший діє в протилежних способах.',
        'Відносини напівдуальності можуть стати дуже близькими на помірні періоди часу. Часто ці відносини призводять до дружби та плідної співпраці на роботі. Але дуже тісні стосунки можуть призвести до розчарувань.'
    ]
}
  